# Generated by Django 5.0.6 on 2024-09-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=252)),
                ('words', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
